
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogic.Data
{

using System;
    using System.Collections.Generic;
    
public partial class forsendelsesRute
{

    public long Id { get; set; }

    public Nullable<long> ForsendelsesId { get; set; }

    public Nullable<long> StartBy { get; set; }

    public Nullable<long> SlutBy { get; set; }

    public long Price { get; set; }

    public int TransportTime { get; set; }



    public virtual forsendelse forsendelse { get; set; }

}

}
