

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogic.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class OADbContext : DbContext
{
    public OADbContext()
        : base("name=OADbContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<by> by { get; set; }

    public DbSet<forsendelse> forsendelse { get; set; }

    public DbSet<forsendelsesRute> forsendelsesRute { get; set; }

    public DbSet<lufthavn> lufthavn { get; set; }

    public DbSet<packetType> packetType { get; set; }

    public DbSet<pakke> pakke { get; set; }

    public DbSet<rute> rute { get; set; }

    public DbSet<users> users { get; set; }

}

}

