//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pakke
    {
        public pakke()
        {
            this.forsendelse = new HashSet<forsendelse>();
        }
    
        public long Id { get; set; }
        public int Weight { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<long> Sender { get; set; }
        public int SizeHight { get; set; }
        public int SizeWidth { get; set; }
        public int SizeDepth { get; set; }
    
        public virtual ICollection<forsendelse> forsendelse { get; set; }
        public virtual packetType packetType { get; set; }
        public virtual users users { get; set; }
    }
}
