//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pakkePris
    {
        public long Id { get; set; }
        public string DimentionsNavn { get; set; }
        public int FromWeight { get; set; }
        public int ToWeight { get; set; }
        public int Price { get; set; }
    
        public virtual pakkeDimintioner pakkeDimintioner { get; set; }
    }
}
