
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessLogic.Data
{

using System;
    using System.Collections.Generic;
    
public partial class rute
{

    public long Id { get; set; }

    public int Time { get; set; }

    public long StartCity { get; set; }

    public long EndCity { get; set; }

}

}
